# 병합/분할

In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.DataFrame({
    "ID": [1, 2, 3, 4],
    "Name": ['홍길동', '신사임당', '이순신', '논개']
})
df2 = pd.DataFrame({
    "ID": [1, 2, 3, 5],
    "Score": [85, 90, 78, 92]
})
display(df1)
display(df2)

   ID  Name
0   1   홍길동
1   2  신사임당
2   3   이순신
3   4    논개

   ID  Score
0   1     85
1   2     90
2   3     78
3   5     92

## 행병합
- merge: column기반 병합 (sql join과 유사)
- join: index기반 병합
- concat

### merge
- merge: column기반 병합

In [3]:
# inner : 두 df에 공통된 행만 병합
pd.merge(df1, df2, on='ID', how='inner')

   ID  Name  Score
0   1   홍길동     85
1   2  신사임당     90
2   3   이순신     78

In [4]:
# left outer : 왼쪽 df의 모든 행 + 오른쪽 df에 공통된 행만 병합
pd.merge(df1, df2, on='ID', how='left')

   ID  Name  Score
0   1   홍길동   85.0
1   2  신사임당   90.0
2   3   이순신   78.0
3   4    논개    NaN

In [5]:
# right outer : 오른쪽 df의 모든 행 + 왼쪽 df에 공통된 행만 병합
pd.merge(df1, df2, on='ID', how='right')

   ID  Name  Score
0   1   홍길동     85
1   2  신사임당     90
2   3   이순신     78
3   5   NaN     92

In [6]:
# outer : 오른쪽 df의 모든 행 + 왼쪽 df에 모든 행 병합
pd.merge(df1, df2, on='ID', how='outer')

   ID  Name  Score
0   1   홍길동   85.0
1   2  신사임당   90.0
2   3   이순신   78.0
3   4    논개    NaN
4   5   NaN   92.0

In [7]:
customer_df = pd.DataFrame({
    'customer_id': [100, 200, 300],
    'name': ['홍길동', '신사임당', '윤봉길']
}).set_index('customer_id') # 일반컬럼을 index로 변환
display(customer_df)

order_df = pd.DataFrame({
    'customer_id': [100, 500],
    'order_id': ['o1', 'o2']
}).set_index('customer_id')
display(order_df)

             name
customer_id
100           홍길동
200          신사임당
300           윤봉길

            order_id
customer_id
100               o1
500               o2

### join
- join: index기반 병합

In [8]:
customer_df.reset_index()

   customer_id  name
0          100   홍길동
1          200  신사임당
2          300   윤봉길

In [9]:
member_df1 = pd.DataFrame({
    'Name': ['홍길동', '이순신'],
    'Age': [33, 48]
})
member_df2 = pd.DataFrame({
    'Name': ['신사임당', '논개'],
    'Age': [27, 55]
})

In [ ]:

# 행고정 df연결 병합

# .reset_index(drop=True): index를 0부터 다시 매기기
member_df = pd.concat([member_df1, member_df2], axis=0).reset_index(drop=True)
member_df

### concat
axix=0 일때, sql union과 유사하게 세로방향 병합이 가능하다.
(동일한 구조의 df을 연결할때 유용하다.)

## 열병합

In [ ]:
score_df = pd.DataFrame({
    "Name": ["홍길동", "신사임당", "이순신"],
    "Math": [85, 90, 78],
    "English": [88, 85, 90],
    "Science": [92, 87, 85]
})
score_df

In [13]:
# melt()
# - id_vars 식별컬럼(기준컬럼)
# - value_vars 병합하고자하는 컬럼명
# - var_name 병합된 컬럼명
# - value_name 값 컬럼명
pd.melt(
    score_df,
    id_vars=['Name'],
    value_vars=['Math', 'English', 'Science'],
    var_name='Subject',
    value_name='Score'
).sort_values('Name').reset_index(drop=True)

   Name  Subject  Score
0  신사임당     Math     90
1  신사임당  English     85
2  신사임당  Science     87
3   이순신     Math     78
4   이순신  English     90
5   이순신  Science     85
6   홍길동     Math     85
7   홍길동  English     88
8   홍길동  Science     92

## 분할